# Generated by Django 3.0.6 on 2020-06-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0003_auto_20200617_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=80, null=True)),
                ('course_pic', models.ImageField(null=True, upload_to='')),
                ('price', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=80, null=True)),
                ('lecturer_lastname', models.CharField(max_length=80, null=True)),
                ('pro_pic', models.ImageField(null=True, upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='super.Course')),
            ],
            options={
                'db_table': 'Lecturer',
            },
        ),
    ]
