# Generated by Django 3.0.6 on 2020-06-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0004_course_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('body', models.TextField(null=True)),
            ],
        ),
    ]
