# Generated by Django 3.0.6 on 2020-06-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0005_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Article',
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
    ]
