# Generated by Django 3.0.6 on 2020-06-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0008_auto_20200618_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cancelled_price',
            field=models.FloatField(null=True),
        ),
    ]
