# Generated by Django 3.0.6 on 2020-06-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0009_course_cancelled_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'Sports',
            },
        ),
    ]
