# Generated by Django 3.0.6 on 2020-06-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0015_event_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
