# Generated by Django 3.0.6 on 2020-06-18 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0019_auto_20200618_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='super.Sport')),
            ],
        ),
    ]
