# Generated by Django 3.0.6 on 2020-06-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0020_schedule'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Events',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='Schedule',
        ),
        migrations.AlterModelTable(
            name='venue',
            table='Venue',
        ),
    ]
