# Generated by Django 3.0.6 on 2020-06-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0021_auto_20200618_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='super.Event'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='super.Venue'),
        ),
    ]
