# Generated by Django 3.0.6 on 2020-06-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0022_auto_20200618_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
