# Generated by Django 3.0.6 on 2020-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0033_auto_20200620_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Fully Booked')], max_length=10),
        ),
    ]
