# Generated by Django 3.0.6 on 2020-06-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0035_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='sports',
        ),
    ]
