# Generated by Django 3.0.8 on 2020-07-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0038_auto_20200621_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
